### ISSUE TITLE
Images disappear

### ISSUE THREAD

**Issue by mbouwmeester** [IcecatNV/magento-extension#3]
Hi, 

If product setting "Update product by Icecat ?" is set to "no", still all images disappear from the product when running the Icecat cronjob. Also when product sku is not matched to Icecat catalog. Do you have a workaround for this issue?

**Comment by IcecatNV** [comment]
Hi,  We could not re-produce the issue at our end, could you provide more details?  

Note : Product should be assigned to a store and images will be downloaded only in the selected stores and only when images download is enabled.

**Comment by mbouwmeester** [comment]
Hi, 
The issue is when you add an image manually to a product in the Magento backend, it will be deleted by this plugin even if the attribute Update product by Icecat ?" is set to "no". Can you please look at this scenario, thnx

**Comment by IcecatNV** [comment]
Hi  @mbouwmeester V2 is live, please verify in V2 and confirm so that i can close this issue.
